### PR TITLE
Fix presets on remote control buttons 0-9

### PR DESCRIPTION
**Pull request by robho**
From reading the [changelog for the community radio firmware](https://ralph_irving.gitlab.io/lms-community-firmware/changelog.html) it seems like buttons 0-9 on the remote control should select presets.

It seems like I need to cherry-pick https://github.com/ralph-irving/squeezeplay/commit/018473bf763c5bcc45713083e4e7959c81b88707 to get it to work. Reasonable? Has this been lost somehow?

### CODE REVIEW

**Comment by ralph-irving** [comment]
Yes, it's not going to work with those lines commented out.  Not sure what happened.
Have you confirmed that removing the comment statement from the beginning of those lines enables preset selection using the numeric keys on the remote?  Just want to be sure nothing else is missing and I won't have time to investigate what happened for a while.

**Comment by robho** [comment]
Yes, I have verified that this PR seems to fix the problem: Before any change, the numeric keys had no effect at all. After making the changes in this PR I can select presets with the numeric keys. I've verified that all presets 0-9 work.

I've been testing with a Squeezebox Radio and a Logitech Harmony remote control (programmed to control a Squeezebox Radio).

**Comment by robho** [comment]
Btw.. I don't know how the community firmware is built. I hope I'm reporting the problem in the right repository :-)

**Comment by ralph-irving** [comment]
Thanks for confirming.
Yes it's the correct repository.  The CF builds pull in sources from a lot of places, so it's not always obvious.

**Comment by ralph-irving** [comment]
I finally had a chance to build firmware r16909 which includes your fix.  Thanks again.

https://sourceforge.net/projects/lmsclients/files/squeezeos/

**Pull request merged**
